sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script:
  - git clone https://github.com/rrwen/assign-rmcs-proposal tex_setmainfont="{Liberation Sans}"
  - cd assign-rmcs-proposal
  - chmod +x make.sh
  - ./make.sh
